### ISSUE TITLE
pipeline_id в animation и text2video

### ISSUE THREAD

**Issue by MastaDan9** [s1rne/kandinsky-async-api#3]
Done!
Error:  {'timestamp': '2024-12-21T01:48:18.154+00:00', 'status': 400, 'error': 'Bad Request', 'message': "Required parameter 'pipeline_id' is not present.", 'path': '/web/api/v1/text2video/run'}
Error:  {'timestamp': '2024-12-21T01:48:18.433+00:00', 'status': 400, 'error': 'Bad Request', 'message': "Required parameter 'pipeline_id' is not present.", 'path': '/web/api/v1/animation/run'}

Привет. На данный момент работает только img генерация через Web. Я попытался заменить pipeline_id в animation и text2video, отлавил запрос, поставил верный pipeline_id, но все равно получаю ошибку

**Comment by s1rne** [comment]
Ты сам решил проблему или всё работало верно? Если нашёл ошибку, я бы исправил в коде для всех

**Comment by s1rne** [comment]
> Done!
> Error:  {'timestamp': '2024-12-21T01:48:18.154+00:00', 'status': 400, 'error': 'Bad Request', 'message': "Required parameter 'pipeline_id' is not present.", 'path': '/web/api/v1/text2video/run'}
> Error:  {'timestamp': '2024-12-21T01:48:18.433+00:00', 'status': 400, 'error': 'Bad Request', 'message': "Required parameter 'pipeline_id' is not present.", 'path': '/web/api/v1/animation/run'}
> 
> Привет. На данный момент работает только img генерация через Web. Я попытался заменить pipeline_id в animation и text2video, отлавил запрос, поставил верный pipeline_id, но все равно получаю ошибку

Ты сам решил проблему или всё работало верно? Если нашёл ошибку, я бы исправил в коде для всех
